In [15]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
import pickle
import pandas

In [16]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)
print((np.array(mnist.data.loc[42]).reshape(28, 28) > 0).astype(int))

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 

In [18]:
X = mnist["data"]
y = mnist["target"].astype(np.uint8)
y.sort_values(inplace=True)
X.reindex(y.index)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
34999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56424     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56419     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
16705     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56415     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
13687     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
42651     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58914     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
13678     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58529     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
34999      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56424      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56419      0.0  ...       0.0       0.0       0.0       0.0       0.0   
16705      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56415      0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
13687      0.0  ...       0.0       0.0       0.0       0.0       0.0   
42651      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58914      0.0  ...       0.0       0.0       0.0       0.0       0.0   
13678      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58529      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
34999       0.0       0.0       0.0       0.0       0.0  
56424       0.0       0.0       0.0       0.0       0.0  
56419       0.0       0.0       0.0       0.0       0.0  
16705       0.0       0.0       0.0       0.0       0.0  
56415       0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
13687       0.0       0.0       0.0       0.0       0.0  
42651       0.0       0.0       0.0       0.0       0.0  
58914       0.0       0.0       0.0       0.0       0.0  
13678       0.0       0.0       0.0       0.0       0.0  
58529       0.0       0.0       0.0       0.0       0.0  

[70000 rows x 784 columns]

In [19]:
X_train, X_test, y_train, y_test = X[:56000], X[56000:], y[:56000], y[56000:]

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
print(np.unique(y_train), np.unique(y_test))

(56000, 784) (56000,)
(14000, 784) (14000,)
[0 1 2 3 4 5 6 7] [7 8 9]


In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
print(np.unique(y_train), np.unique(y_test))

(56000, 784) (56000,)
(14000, 784) (14000,)
[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


In [22]:
X = mnist["data"]
y = mnist["target"].astype(np.uint8)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)
y_train_0 = (y_train == 0)
y_test_0 = (y_test == 0)
print(np.unique(y_train_0))

[False  True]


In [23]:
sgd_clf_0 = SGDClassifier(n_jobs=-1)
sgd_clf_0.fit(X_train, y_train_0)

SGDClassifier(n_jobs=-1)

In [25]:
train_accuracy_0 = sgd_clf_0.score(X_train, y_train_0)
test_accuracy_0 = sgd_clf_0.score(X_test, y_test_0)
print("Train accuracy: ", train_accuracy_0)
print("Test accuracy: ", test_accuracy_0)

with open('sgd_acc.pkl', 'wb') as f:
    pickle.dump([train_accuracy_0, test_accuracy_0], f)

Train accuracy:  0.9907857142857143
Test accuracy:  0.99


In [31]:
from sklearn.model_selection import cross_val_score
score_0 = cross_val_score(sgd_clf_0, X_train, y_train_0,cv=3, scoring="accuracy", n_jobs=-1)
print("Cross validation score: ", score_0)

with open('sgd_cva.pkl', 'wb') as f:
    pickle.dump(np.array(score_0), f)

Cross validation score:  [0.98676809 0.98698238 0.98505304]


In [28]:
sgd_clf = SGDClassifier()
sgd_clf.fit(X_train, y_train)

SGDClassifier()

In [30]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
y_train_pred = sgd_clf.predict(X_train)
c_mx = confusion_matrix(y_train, y_train_pred)
print(c_mx)

with open('sgd_cmx.pkl', 'wb') as f:
    pickle.dump(c_mx, f)

[[5292    0   30    5    9   16   22    1   39   83]
 [   2 5819   59    1    7  123   39    3  104  122]
 [  29    8 5057   25   40   24   62   21  226   83]
 [  30   10  235 4056   15  437   53   26  246  591]
 [   6    7   39    2 4598   12   26    3   21  711]
 [  43    5   37   21   52 4476   86   11  156  163]
 [  30    5   73    2   29   88 5270    0   41   17]
 [  18    0   75   16   58    7    7 4699   29  937]
 [  25   21   70   31   31  259   55    5 4144  823]
 [   6    4   22   13   57   28    1   26   25 5428]]
